service:
  name: 2ndcareers-api
  port: 5000
  start:
    command: python app.py
  readiness_check:
    command: curl -fsS http://localhost:5000/health
    timeout: 30s
    interval: 1s
  id: 13225c22-1bbf-445c-9e13-cd0a99c150dd

traces:
  dir: .tusk/traces

test_execution:
  timeout: 30s

recording:
  sampling_rate: 1.0
  export_spans: true
  enable_env_var_recording: false
